org: georgedavisibexlabs
app: aws-python-stack-outputs-api
service: aws-python-stack-outputs-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  runtimeManagement: auto # optional, set how Lambda controls all functions runtime. AWS default is auto; this can either be 'auto' or 'onFunctionUpdate'. For 'manual', see example in hello function below (syntax for both is identical)
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 25 # HTTP Timeout, in seconds, limited to 30 seconds.
  versionFunctions: false # optional, default is true
  tracing:
    lambda: true 

package:
  individually: true

functions:
  postStackOutputLambda:
    handler: postStackOutputLambda.lambda_handler    
    environment:
      LOG_LEVEL: DEBUG
    events:
      - httpApi:
          path: /send
          method: post
    package:
      patterns:
        - postStackOutputLambda.py
        - slack_block_generator.py

plugins:
  - serverless-dotenv-plugin
